version: "3.8"

services:
  app:
    build: .
    container_name: my_app
    depends_on:
      - postgres
    entrypoint: ["/app/entrypoint.sh"]
    command: ["python", "-m", "app.main"]  # run main from the app package
    volumes:
      - ./logs/sql:/app/logs/sql
      - ./logs/runner:/app/logs/runner
      - ./config/api_key.txt:/app/config/api_key.txt:ro  # mount the API key file
    networks:
      - default

  postgres:
    image: postgres:13
    container_name: postgres
    command: ["postgres", "-c", "max_wal_size=2GB"]
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./tpc-data:/tpc-data
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    driver: bridge
